#!/bin/bash

ENI_ID="eni-02497ff2c6f93eef9"
ENI_IP="172.31.1.100"
ENI_MASK="255.255.255.0"
ENI_GW="172.31.0.1"
ETH_DEVICE_INDEX="2"
ENI2="7"
ETHX="ens"$[$ENI2]

curl -O https://bootstrap.pypa.io/get-pip.py || (echo "Error while downloading pip." && exit 1)
python3 get-pip.py --user || (echo "Error while installing pip." && exit 1)
~/.local/bin/pip install awscli --upgrade --user || (echo "Error while installing awscli." && exit 1)

INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}')
~/.local/bin/aws ec2 attach-network-interface --region $REGION --instance-id $INSTANCE_ID --device-index $ETH_DEVICE_INDEX --network-interface-id $ENI_ID

sudo touch /etc/network/interfaces.d/$ETHX.cfg
sudo bash -c "echo 'auto' $ETHX >> /etc/network/interfaces.d/$ETHX.cfg"
sudo bash -c "echo 'iface' $ETHX 'inet static'>> /etc/network/interfaces.d/$ETHX.cfg"
sudo bash -c "echo 'address' $ENI_IP >> /etc/network/interfaces.d/$ETHX.cfg"
sudo bash -c "echo 'netmask' $ENI_MASK >> /etc/network/interfaces.d/$ETHX.cfg"
sudo bash -c "echo 'gateway' $ENI_GW >> /etc/network/interfaces.d/$ETHX.cfg"
